### ISSUE TITLE
Plotting issue when running chrysalis on integrated samples

### ISSUE THREAD

**Issue by ahmetrifaioglu** [rockdeme/chrysalis#1]
Hi,

Thanks again for the great work. I could run Chrysalis per sample without any problem. However, when I try to run it multiple samples I am getting the following error. That would be great if you could let me the possible cause of this error. Here is the traceback:

```
Traceback (most recent call last):
  File "vis_tissue_compartment.py", line 69, in <module>
    ch.plot(adata, dim=10, sample_id=i, rasterized=True)
  File "/Users/ahmet/opt/anaconda3/envs/chrysalis-env/lib/python3.8/site-packages/chrysalis/plots.py", line 101, in plot
    row_range = np.ptp(row)
  File "<__array_function__ internals>", line 200, in ptp
  File "/Users/ahmet/opt/anaconda3/envs/chrysalis-env/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2694, in ptp
    return ptp(axis=axis, out=out, **kwargs)
  File "/Users/ahmet/opt/anaconda3/envs/chrysalis-env/lib/python3.8/site-packages/numpy/core/_methods.py", line 283, in _ptp
    umr_maximum(a, axis, None, out, keepdims),
  File "/Users/ahmet/opt/anaconda3/envs/chrysalis-env/lib/python3.8/site-packages/anndata/_core/views.py", line 113, in __array_ufunc__
    results = super().__array_ufunc__(
ValueError: zero-size array to reduction operation maximum which has no identity
```

**Here is the related code chunk:**
```
print("running scanorama.correct_scanpy...")
adatas_cor = scanorama.correct_scanpy(adatas, return_dimred=True)
print("running ch.integrate_adatas...")
adata = ch.integrate_adatas(adatas_cor)
adata.write(os.path.join(output_path, f'chrysalis_{sample_group}_integrated.h5ad'))

# adata = sc.read_h5ad(os.path.join(output_path, f'chrysalis_{sample_group}_integrated.h5ad'))


adata.var.index = adata.var['gene_symbols']
adata.var_names = adata.var['gene_symbols']
print(adata)
ch.pca(adata)

ch.plot_explained_variance(adata)
plt.savefig(os.path.join(PLOT_PATH, "explained_variance.pdf"), dpi=300)

ch.aa(adata, n_pcs=20, n_archetypes=10)

for i in np.unique(adata.obs['sample_id']):
    ch.plot(adata, dim=10, sample_id=i, rasterized=True)
    plt.savefig(os.path.join(PLOT_PATH, f"{i}_explained_variance.pdf"), dpi=300)

for i in np.unique(adata.obs['sample_id']):
    ch.plot_compartments(adata, sample_id=i, ncols=5, rasterized=True, title_size=15)
    plt.savefig(os.path.join(PLOT_PATH, f"{i}_compartments.pdf"), dpi=300)

ch.plot_weights(adata, ncols=5)
plt.savefig(os.path.join(PLOT_PATH, f"loadings.pdf"), dpi=300)
```
**Libray versions:**
```
access==1.1.9
affine==2.4.0
anndata==0.9.2
annoy==1.17.3
appnope==0.1.3
archetypes==0.4.2
asttokens==2.4.0
attrs==23.1.0
backcall==0.2.0
beautifulsoup4==4.12.2
certifi==2023.7.22
charset-normalizer==3.2.0
chrysalis-st==0.1.1
click==8.1.7
click-plugins==1.1.1
cligj==0.7.2
contourpy==1.1.0
cycler==0.11.0
decorator==5.1.1
deprecation==2.1.0
esda==2.5.0
executing==1.2.0
fbpca==1.0
Fiona==1.9.4.post1
fonttools==4.42.1
geopandas==0.13.2
geosketch==1.2
giddy==2.3.4
h5py==3.9.0
idna==3.4
importlib-metadata==6.8.0
importlib-resources==6.0.1
inequality==1.0.0
intervaltree==3.1.0
ipython==8.12.2
jedi==0.19.0
Jinja2==3.1.2
joblib==1.3.2
kiwisolver==1.4.5
libpysal==4.7.0
llvmlite==0.40.1
mapclassify==2.6.0
MarkupSafe==2.1.3
matplotlib==3.7.3
matplotlib-inline==0.1.6
mgwr==2.1.2
momepy==0.6.0
mpmath==1.3.0
natsort==8.4.0
networkx==3.1
numba==0.57.1
numpy==1.24.4
packaging==23.1
pandas==2.0.3
parso==0.8.3
patsy==0.5.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==10.0.0
platformdirs==3.10.0
pointpats==2.3.0
prompt-toolkit==3.0.39
ptyprocess==0.7.0
PuLP==2.7.0
pure-eval==0.2.2
pygeos==0.14
Pygments==2.16.1
```

**Comment by rockdeme** [comment]
Hi @ahmetrifaioglu!

Thanks again for using Chrysalis! Based on the error, it looks like that your `adata` object has zero elements in the `.obsm['spatial']` matrix for a particular sample_id. 

To look into it further, could you check if the sample_id in question has any rows/spatial coordinates assigned to it? You can subset the integrated AnnData object using the sample_id you have issues with:

```python
ad = adata[adata.obs['sample'] == 'your_id']
print(len(ad))
print(len(ad.obsm['spatial']))
```

**Comment by ahmetrifaioglu** [comment]
Hi @rockdeme,

I am sorry for the late response, I was stuck among the other things. Thanks for the suggestion. I just checked the .obsm['spatial'] and the coordinates exist. What might be the other causes of this issue?

**Comment by ahmetrifaioglu** [comment]
Hi @rockdeme, 

Thanks! I found out that the issue is related my obs column. After digging in the code and checking the documentation again, apparently I mixed the `sample_id` parameter in plotting functions and the obs column name `sample`. I realised that the integrated object is subsampled by obs column `sample` whereas the obs column in my integrated object is named as `sample_id`. In addition, it seems scanpy or scanorama automatically creates an obs column `sample` if it does not exist and it assigns values from `0` to `number of samples` for each sample. Therefore, in my case `sample` column exists  but the names do not match with the `sample_id` parameter that I provide which results in an empty anndata object after subsampling.  Now, it works!

**Comment by ahmetrifaioglu** [comment]
Thanks for your answer. Yes, that would be great if users can customise the obs column name. Regarding the integration, that would be nice to add other widely used integration methods or if the method accepts already integrated object.

**Comment by rockdeme** [comment]
> Hey @ahmetrifaioglu! Just wanted to let you know that there is a new tutorial available on sample integration with `harmony` and `scanorama`: https://chrysalis.readthedocs.io/en/latest/tutorials/advanced_integration_tutorial.html

Closing the issue for now.

**Comment by rockdeme** [comment]
> Hey @ahmetrifaioglu! Just wanted to let you know that there is a new tutorial available on sample integration with `harmony` and `scanorama`: https://chrysalis.readthedocs.io/en/latest/tutorials/advanced_integration_tutorial.html

Closing the issue for now.
